import {
  AcademicCapSolid,
  Adjustments,
  ArchiveBox,
  ArrowDownLeftMini,
  ArrowDownTray,
  ArrowPath,
  ArrowUpRightOnBox,
  ArrowUturnLeft,
  BarsThree,
  BellAlert,
  BellAlertSolid,
  Bolt,
  BoltSolid,
  BookOpen,
  Bug,
  BugAntSolid,
  BuildingStorefront,
  BuildingTax,
  BuildingsSolid,
  Calendar,
  CashSolid,
  Channels,
  ChannelsSolid,
  CheckCircleSolid,
  CheckMini,
  ChevronDoubleLeftMiniSolid,
  ChevronUpDown,
  CircleDottedLine,
  CircleMiniSolid,
  CircleStack,
  CircleStackSolid,
  ClockSolidMini,
  CloudArrowUp,
  CogSixTooth,
  CogSixToothSolid,
  CommandLine,
  CommandLineSolid,
  ComponentSolid,
  ComputerDesktop,
  ComputerDesktopSolid,
  CreditCardSolid,
  CubeSolid,
  CurrencyDollar,
  CurrencyDollarSolid,
  Discord,
  DocumentText,
  DocumentTextSolid,
  EllipseMiniSolid,
  Envelope,
  ExclamationCircle,
  ExclamationCircleSolid,
  FlyingBox,
  Folder,
  FolderOpen,
  Gatsby,
  GiftSolid,
  GlobeEurope,
  GlobeEuropeSolid,
  InformationCircleSolid,
  JavascriptEx,
  Key,
  KeySolid,
  LightBulb,
  LightBulbSolid,
  Linkedin,
  MagnifyingGlass,
  Map,
  Moon,
  Newspaper,
  PencilSquareSolid,
  Puzzle,
  ReactJsEx,
  ReceiptPercent,
  RocketLaunch,
  Server,
  ServerSolid,
  ServerStack,
  ServerStackSolid,
  ShoppingCart,
  ShoppingCartSolid,
  SidebarLeft,
  Sparkles,
  SparklesSolid,
  SquareTwoStackSolid,
  SquaresPlus,
  SquaresPlusSolid,
  Star,
  StarSolid,
  Stripe,
  Sun,
  Swatch,
  SwatchSolid,
  TagSolid,
  Tools,
  ToolsSolid,
  Twitter,
  User,
  UsersSolid,
  XCircleSolid,
  XMark,
  XMarkMini,
  PhotoSolid,
  ListBullet,
  Medusa,
  Heart,
  QuestionMark,
  ChatBubbleLeftRight,
  Window,
} from '@medusajs/icons';
import IconPuzzleSolid from './PuzzleSolid';
import IconNextjs from './Nextjs';
import IconFlagMini from './FlagMini';
import IconBeaker from './Beaker';
import IconGitHub from './GitHub';
import IconNestjs from './Nestjs';
import IconLaravel from './Laravel';
import IconGingonic from './Gingonic';
import IconNette from './Nette';
import IconStrapi from './Strapi';
import IconNodejs from './Nodejs';
import IconPhp from './Php';
import IconGo from './Go';
import IconPython from './Python';
import IconDotnet from './Dotnet';
import IconRust from './Rust';
import IconJava from './Java';
import IconPostgresql from './Postgresql';
import IconMariadb from './Mariadb';
import IconMeilisearch from './Meilisearch';
import IconMongodb from './Mongodb';
import IconElasticsearch from './Elasticsearch';
import IconKeydb from './Keydb';
import IconRabbitmq from './Rabbitmq';
import IconNginx from './Nginx';
import IconUbuntu from './Ubuntu';
import IconDeno from './Deno';
import IconBun from './Bun';
import IconGleam from './Gleam';
import IconElixir from './Elixir';
import IconQdrant from './Qdrant';
import IconNats from './Nats';
import IconKafka from './Kafka';
import IconValkey from './Valkey';
import IconAlpine from './Alpine';
import IconFirewall from './Firewall';
import IconZerops from './Zerops';
import IconDatabase from './Database';
import IconCloudOk from './CloudOk';


export default {
  'academic-cap-solid': AcademicCapSolid,
  adjustments: Adjustments,
  alert: ExclamationCircleSolid,
  'archive-box': ArchiveBox,
  'arrow-down-left-mini': ArrowDownLeftMini,
  'arrow-down-tray': ArrowDownTray,
  'arrow-path': ArrowPath,
  'back-arrow': ArrowUturnLeft,
  'bars-three': BarsThree,
  beaker: IconBeaker,
  bell: BellAlert,
  'bell-alert-solid': BellAlertSolid,
  bolt: Bolt,
  'bolt-solid': BoltSolid,
  'book-open': BookOpen,
  bug: Bug,
  'bug-ant-solid': BugAntSolid,
  'building-solid': BuildingsSolid,
  'building-storefront': BuildingStorefront,
  'building-tax': BuildingTax,
  calendar: Calendar,
  'cash-solid': CashSolid,
  'channels-solid': ChannelsSolid,
  channels: Channels,
  'check-circle-solid': CheckCircleSolid,
  'check-mini': CheckMini,
  'chevron-double-left-mini-solid': ChevronDoubleLeftMiniSolid,
  'chevron-up-down': ChevronUpDown,
  'circle-dotted-line': CircleDottedLine,
  'circle-mini-solid': CircleMiniSolid,
  'circle-stack': CircleStack,
  'circle-stack-solid': CircleStackSolid,
  'clock-solid-mini': ClockSolidMini,
  close: XMark,
  'cloud-arrow-up': CloudArrowUp,
  'cog-six-tooth': CogSixTooth,
  'cog-six-tooth-solid': CogSixToothSolid,
  'command-line': CommandLine,
  'command-line-solid': CommandLineSolid,
  'component-solid': ComponentSolid,
  'computer-desktop': ComputerDesktop,
  'computer-desktop-solid': ComputerDesktopSolid,
  copy: SquareTwoStackSolid,
  'credit-card-solid': CreditCardSolid,
  'cube-solid': CubeSolid,
  'currency-dollar': CurrencyDollar,
  'currency-dollar-solid': CurrencyDollarSolid,
  'dark-mode': Moon,
  discord: Discord,
  'document-text': DocumentText,
  'document-text-solid': DocumentTextSolid,
  'ellipse-mini-solid': EllipseMiniSolid,
  'envelope': Envelope,
  'exclamation-circle-solid': ExclamationCircleSolid,
  'external-link': ArrowUpRightOnBox,
  'flying-box': FlyingBox,
  folder: Folder,
  'folder-open': FolderOpen,
  gatsby: Gatsby,
  'gift-solid': GiftSolid,
  'flag-mini': IconFlagMini,
  'firewall': IconFirewall,
  github: IconGitHub,
  'globe-europe': GlobeEurope,
  'globe-europe-solid': GlobeEuropeSolid,
  'information-circle-solid': InformationCircleSolid,
  javascript: JavascriptEx,
  key: Key,
  'key-solid': KeySolid,
  'light-bulb': LightBulb,
  'light-bulb-solid': LightBulbSolid,
  'light-mode': Sun,
  linkedin: Linkedin,
  'magnifying-glass': MagnifyingGlass,
  map: Map,
  newspaper: Newspaper,
  nextjs: IconNextjs,
  'pencil-square-solid': PencilSquareSolid,
  'photo-solid': PhotoSolid,
  puzzle: Puzzle,
  // TODO change once available in Icons package
  'puzzle-solid': IconPuzzleSolid,
  react: ReactJsEx,
  'receipt-percent': ReceiptPercent,
  report: ExclamationCircle,
  'rocket-launch': RocketLaunch,
  server: Server,
  'server-solid': ServerSolid,
  'server-stack': ServerStack,
  'server-stack-solid': ServerStackSolid,
  'shopping-cart': ShoppingCart,
  'shopping-cart-solid': ShoppingCartSolid,
  sidebar: SidebarLeft,
  sparkles: Sparkles,
  'sparkles-solid': SparklesSolid,
  'squares-plus': SquaresPlus,
  'squares-plus-solid': SquaresPlusSolid,
  star: Star,
  'star-solid': StarSolid,
  stripe: Stripe,
  'swatch-solid': SwatchSolid,
  'tag-solid': TagSolid,
  tools: Tools,
  'tools-solid': ToolsSolid,
  twitter: Twitter,
  user: User,
  'users-solid': UsersSolid,
  'x-circle-solid': XCircleSolid,
  'x-mark': XMark,
  'x-mark-mini': XMarkMini,
  'question-mark': QuestionMark,
  'chat-bubble-left-right': ChatBubbleLeftRight,
  heart: Heart,
  nestjs: IconNestjs,
  laravel: IconLaravel,
  gingonic: IconGingonic,
  nette: IconNette,
  strapi: IconStrapi,
  medusa: Medusa,
  nodejs: IconNodejs,
  'list-bullet': ListBullet,
  window: Window,
  swatch: Swatch,
  php: IconPhp,
  go: IconGo,
  python: IconPython,
  dotnet: IconDotnet,
  rust: IconRust,
  java: IconJava,
  postgresql: IconPostgresql,
  mariadb: IconMariadb,
  meilisearch: IconMeilisearch,
  mongodb: IconMongodb,
  elasticsearch: IconElasticsearch,
  keydb: IconKeydb,
  rabbitmq: IconRabbitmq,
  nginx: IconNginx,
  ubuntu: IconUbuntu,
  deno: IconDeno,
  bun: IconBun,
  gleam: IconGleam,
  elixir: IconElixir,
  qdrant: IconQdrant,
  nats: IconNats,
  kafka: IconKafka,
  valkey: IconValkey,
  alpine: IconAlpine,
  zerops: IconZerops,
  database: IconDatabase,
  cloudok: IconCloudOk,
};
